# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain Java versions, and provides a first line of defence against bad commits.

name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        java: [ "8" ] # JDK 8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: gradle/wrapper-validation-action@v1.1.0
      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
      - name: Grant execute permission
        run: chmod +x ./gradlew
      - name: Set up Gradle build
        run: ./gradlew SetupCIWorkspace build
      - name: Build with Gradle
        run: ./gradlew cleanBuildAll
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.0
        with: 
          name: Neodymium
          path: build/libs/*.jar
